# Generated by Django 3.0.2 on 2020-02-13 12:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('socialService', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='comments',
            options={'managed': False, 'ordering': ['-created_dt']},
        ),
        migrations.AlterModelOptions(
            name='posts',
            options={'managed': False, 'ordering': ['-created_dt']},
        ),
    ]
